Document: osm2xmap
Title: Debian osm2xmap Manual
Author: <insert document author here>
Abstract: This manual describes what osm2xmap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/osm2xmap/osm2xmap.sgml.gz

Format: postscript
Files: /usr/share/doc/osm2xmap/osm2xmap.ps.gz

Format: text
Files: /usr/share/doc/osm2xmap/osm2xmap.text.gz

Format: HTML
Index: /usr/share/doc/osm2xmap/html/index.html
Files: /usr/share/doc/osm2xmap/html/*.html
